USE FUNCTIONALGYM;

-- Insertar datos en la tabla ESTANCIA
INSERT INTO ESTANCIA (ID, NOMBRE, FECHA_CREACION, FECHA_MODIFICACION) VALUES
(1, 'Primera sala', NOW(), NOW()),
(2, 'Segunda sala', NOW(), NOW());

-- Insertar datos en la tabla ESTADO
INSERT INTO ESTADO (ID, TIPO, NAME, FECHA_CREACION) VALUES
(1, 'CLIENTE', 'ACTIVO', NOW()),
(2, 'CLIENTE', 'BAJA', NOW()),
(3, 'CLIENTE', 'USUARIO NO ACTIVO', NOW()),
(4, 'CLIENTE', 'INTERMITENTE', NOW()),
(5, 'RESERVA', 'INSCRITO', NOW()),
(6, 'RESERVA', 'REALIZADO', NOW()),
(7, 'RESERVA', 'CANCELADO', NOW()),
(8, 'RESERVA', 'COLA', NOW());

-- Insertar datos en la tabla CALENDARIO
INSERT INTO CALENDARIO (ID, NOMBRE, DESCRIPCION, FECHA_CREACION, FECHA_MODIFICACION) VALUES
(1, 'CALENDARIO POR DEFECTO', 'ESTE ES EL CALENDARIO POR DEFECTO', NOW(), NOW());

-- Insertar datos en la tabla SUSCRIPCION
INSERT INTO SUSCRIPCION (NOMBRE, DESCRIPCION, FECHA_CREACION, FECHA_MODIFICACION, ACTIVO) VALUES
('SUSCRIPCION GENERICA', '', NOW(), NOW(), TRUE);
