USE FUNCTIONALGYM;

-- Deshabilitar el modo seguro temporalmente
SET SQL_SAFE_UPDATES = 0;

-- Eliminar registros de la tabla ESTANCIA
DELETE FROM ESTANCIA;

-- Eliminar registros de la tabla ESTADO
DELETE FROM ESTADO; 

-- Eliminar registros de la tabla CONFIGURACION_GENERAL
DELETE FROM CONFIGURACION_GENERAL;

-- Eliminar registros de la tabla CONFIGURACION_SUSCRIPCION
DELETE FROM CONFIGURACION_SUSCRIPCION;

DELETE FROM CLASE;

-- Eliminar registros de la tabla SUSCRIPCION
DELETE FROM SUSCRIPCION;

DELETE FROM DURACION;

DELETE FROM TIPO_CLASE;

DELETE FROM INTENSIDAD;

DELETE FROM CALENDARIO;

-- Volver a habilitar el modo seguro
SET SQL_SAFE_UPDATES = 1;