USE FUNCTIONALGYM;

-- Table: USUARIO
CREATE TABLE USUARIO (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    IX VARCHAR(7) NOT NULL UNIQUE,
    USERNAME VARCHAR(35) UNIQUE,
    PASSWORD VARCHAR(12),
    ROL INT,
    FECHA_CREACION DATE,
    FECHA_MODIFICACION DATE,
    ACTIVO BOOLEAN
);

-- Table: PERSONA
CREATE TABLE PERSONA (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(30),
    TIPO_PERSONA INT,
    APELLIDOS VARCHAR(50),
    FECHA_NACIMIENTO DATE,
    TELEFONO VARCHAR(9),
    FECHA_CREACION DATE,
    FECHA_MODIFICACION DATE,
	EMAIL VARCHAR(50),
	DESCRIPCION VARCHAR(200),
	IMAGENURL VARCHAR(100),
    IX_USUARIO VARCHAR(7),
    FOREIGN KEY (IX_USUARIO) REFERENCES USUARIO(IX)
);

-- Table: ESTANCIA
CREATE TABLE ESTANCIA (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(35),
    FECHA_CREACION DATE,
    FECHA_MODIFICACION DATE
);

-- Table: ESTADO
CREATE TABLE ESTADO (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    TIPO VARCHAR(30),
    NAME VARCHAR(35),
    FECHA_CREACION DATE
);

-- Table: ESTADO_CLIENTE
CREATE TABLE ESTADO_CLIENTE (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    ID_ESTADO INT,
    ID_CLIENTE INT,
    MOTIVO INT NOT NULL,
    FECHA_CREACION DATE,
    FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO(ID),
    FOREIGN KEY (ID_CLIENTE) REFERENCES USUARIO(ID)
);

-- Table: INTENSIDAD
CREATE TABLE INTENSIDAD (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    VALUE VARCHAR(20),
    COLOR VARCHAR(50),
    FECHA_CREACION DATE
);

-- Table: TIPO_CLASE
CREATE TABLE TIPO_CLASE (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    VALUE VARCHAR(30),
    COLOR VARCHAR(50),
    FECHA_CREACION DATE
);

-- Table: DURACION
CREATE TABLE DURACION (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    VALUE VARCHAR(35),
    FECHA_CREACION DATE
);

-- Table: CLASE
CREATE TABLE CLASE (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(35),
    DESCRIPCION VARCHAR(255),
    FECHA_CREACION DATE,
    FECHA_MODIFICACION DATE,
    ESTADO BOOLEAN,
    AFORO_MAX INT,
	COLOR VARCHAR(30),
	ID_INTENSIDAD INT,
	ID_TIPO_CLASE INT,
	ID_DURACION INT,
	FOREIGN KEY (ID_INTENSIDAD) REFERENCES INTENSIDAD(ID),
	FOREIGN KEY (ID_DURACION) REFERENCES DURACION(ID),
    FOREIGN KEY (ID_TIPO_CLASE) REFERENCES TIPO_CLASE(ID)
);

-- Table: CALENDARIO
CREATE TABLE CALENDARIO (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(35),
    DESCRIPCION VARCHAR(255),
    FECHA_CREACION DATE,
    FECHA_MODIFICACION DATE
);

-- Table: SUSCRIPCION
CREATE TABLE SUSCRIPCION (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(35),
	PRECIO VARCHAR(10),
    DESCRIPCION VARCHAR(255),
    FECHA_CREACION DATE,
    FECHA_MODIFICACION DATE,
    ACTIVO BOOLEAN
);

-- Table: CONFIGURACION_SUSCRIPCION
CREATE TABLE CONFIGURACION_SUSCRIPCION (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    VALUE VARCHAR(35),
    ID_SUSCRIPCION INT,
    DESCRIPCION VARCHAR(255),
    FECHA_CREACION DATE,
    FECHA_MODIFICACION DATE,
	ESTADO BOOLEAN,
    FOREIGN KEY (ID_SUSCRIPCION) REFERENCES SUSCRIPCION(ID)
);

-- Table: CONFIGURACION_GENERAL
CREATE TABLE CONFIGURACION_GENERAL (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(35),
	VALUE VARCHAR(30),
	DESCRIPCION VARCHAR(255),
    FECHA_CREACION DATE,
    FECHA_MODIFICACION DATE,
	ESTADO BOOLEAN
);

-- Table: CLIENTE_SUSCRIPCION
CREATE TABLE CLIENTE_SUSCRIPCION (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    FECHA_CREACION DATE,
    FECHA_MODIFICACION DATE,
    ID_CLIENTE INT,
    ID_SUSCRIPCION INT,
    FECHA_INICIO DATE,
    FECHA_FIN DATE,
	ESTADO VARCHAR(30),
    FOREIGN KEY (ID_CLIENTE) REFERENCES USUARIO(ID),
    FOREIGN KEY (ID_SUSCRIPCION) REFERENCES SUSCRIPCION(ID)
);

-- Table: PLANIFICACION
CREATE TABLE PLANIFICACION (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    FECHA_MODIFICACION DATE,
	FECHA_CREACION DATE,
    ID_CLASE INT,
    ID_CALENDARIO INT,
    ID_ENTRENADOR INT,
    ID_ESTANCIA INT,
    DIA_EJECUCION DATE,
    HORA_INICIO VARCHAR(30),
    ESTADO BOOLEAN,
    MOSTRAR BOOLEAN,
    PERMANENTE BOOLEAN,
    FOREIGN KEY (ID_CLASE) REFERENCES CLASE(ID),
    FOREIGN KEY (ID_CALENDARIO) REFERENCES CALENDARIO(ID),
    FOREIGN KEY (ID_ENTRENADOR) REFERENCES USUARIO(ID),
    FOREIGN KEY (ID_ESTANCIA) REFERENCES ESTANCIA(ID)
);

-- Table: RESERVA
CREATE TABLE RESERVA (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    FECHA_CREACION DATE,
    FECHA_MODIFICACION DATE,
    ID_CLIENTE INT,
    ID_PLANIFICACION INT,
    FOREIGN KEY (ID_CLIENTE) REFERENCES USUARIO(ID),
    FOREIGN KEY (ID_PLANIFICACION) REFERENCES PLANIFICACION(ID)
);

-- Table: RESERVA_ESTADOS
CREATE TABLE RESERVA_ESTADOS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    ID_RESERVA INT,
    ID_ESTADO INT,
    FECHA_CREACION DATE,
    FOREIGN KEY (ID_RESERVA) REFERENCES RESERVA(ID),
    FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO(ID)
);

-- Table: QR
CREATE TABLE QR (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    QR_VALUE VARCHAR(10),
    FECHA_CREACION BIGINT,
    IX_USUARIO VARCHAR(7),
    ID_RESERVA INT,
    ESTADO BOOLEAN,
    FOREIGN KEY (IX_USUARIO) REFERENCES USUARIO(IX),
    FOREIGN KEY (ID_RESERVA) REFERENCES RESERVA(ID)
);

-- Table: CONTROL_ACCESO
CREATE TABLE CONTROL_ACCESO (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    ID_QR INT,
    ID_ESTANCIA INT,
    FECHA_CREACION DATE,
    TIPO VARCHAR(25),
    RESULTADO BOOLEAN,
    FOREIGN KEY (ID_QR) REFERENCES QR(ID),
    FOREIGN KEY (ID_ESTANCIA) REFERENCES ESTANCIA(ID)
);


-- Table: CODIGO_VALIDACION
CREATE TABLE CODIGO_VALIDACION (
    ID INT PRIMARY KEY AUTO_INCREMENT,
	IX_CLIENTE VARCHAR(7),
	VALUE VARCHAR(10),
	TYPE VARCHAR(20),
    FECHA_CREACION DATE,
    FOREIGN KEY (IX_CLIENTE) REFERENCES USUARIO(IX)
);